version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: rate-limiter
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus